---
title: "Model Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(ggthemes)
library(httr)
library(tibble)

model_endpoint <- "https://colorado.rstudio.com/rsc/model-management/model-router/predict"

get_results <- reactive({
  
  invalidateLater(input$frequency * 1000, session = getDefaultReactiveDomain())
  
  if (input$payment_history == 1) {
    payment_months <- c(-1, -1, -1)
  } else if (input$payment_history == 2) {
    payment_months <- c(2, 3, 4)
  } else if (input$payment_history == 3) {
    payment_months <- c(7, 8, 9)
  }
  
  results <- data.frame(matrix(ncol = 3, nrow = 0))
  colnames(results) <- c("prediction", "model", "time")
  for (i in c(1:input$hits)){
    months <- sample(payment_months, 1)
    payment <- strrep(paste0(months, ","), 6)
    model_inputs <- paste0("35,500000,1,1,1,58,", payment, "13709,5006,31130,3180,0,5293,5006,31178,3180,0,5293,768")
    
    start_time <- proc.time()
    r <- POST(model_endpoint,
              body = list(input = model_inputs),
              encode = "json")
    time <- proc.time() - start_time
    
    result <- content(r)
    new_row <- data.frame(result$prediction, result$model, time[3])
    colnames(new_row) <- c("prediction", "model", "time")
    results <- rbind(results, new_row)
  }
  rownames(results) <- 1:nrow(results)
  results
})
```

Row {data-height=200}
-------------------------------------

### Inputs

```{r}
numericInput("hits",
             "Number of Model Queries",
             10,
             min = 1,
             max = 100)

numericInput("frequency",
             "Refresh Interval",
             10,
             min = 1,
             max = 100)
```

### Payment History

```{r}
radioButtons(
  "payment_history",
  label = h3("Payment History"),
  choices = list(
    "On Time" = 1,
    "2 to 4 Months Late" = 2,
    "7 to 9 Months Late" = 3
  )
)
```

Row
-------------------------------------

### API Hits

```{r}
renderValueBox({
  valueBox(input$hits,
           icon = "fa-server",
           color = "#89AAE6")
})
```

### Average round trip time

```{r}
renderValueBox({
  results <- get_results()
  valueBox(paste0(round(mean(results$time), 2), " ms"),
           icon = "fa-clock",
           color = "#3685B5")
})
```

### Model A Average Probability

```{r}
renderValueBox({
  results <- get_results()
  valueBox(round(mean(results$prediction[results$model == "model-a"]), 2),
           icon = "fa-clock",
           color = "#0471A6")
})
```

### Model B Average Probability

```{r}
renderValueBox({
  results <- get_results()
  valueBox(round(mean(results$prediction[results$model == "model-b"]), 2),
           icon = "fa-clock",
           color = "#0471A6")
})
```

Row
-------------------------------------
    
### Model Diagnostics


```{r}
  renderPlot({
    results <- get_results()
    ggplot(results, aes(as.numeric(rownames(results)), prediction,
                        color = model)) +
      geom_point(size = 5) +
      ylim(0, 1) +
      xlab("API Request Number") +
      ylab("Probability of Default on Credit Payment") +
      theme_clean(base_size = 16)
  })
```
