default:
  model_config:
    id: "model-b"
    path_prefix: "../"
    path_suffix: "-predict/model/xgb.model"

rsconnect:
  model_config:
    id: "model-b"
    path_prefix: "./"
    path_suffix: ".xgb.model"
